Website_BanHang/Areas/Admin/Controllers/ProductADController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using Website_BanHang.Context;

using static Website_BanHang.Common;

namespace Website_BanHang.Areas.Admin.Controllers
{
    public class ProductADController : Controller
    {
        Website_BanHangEntities objWebASP = new Website_BanHangEntities();
        // GET: Admin/ProductAD
        public ActionResult Index(string SearchString, string currentFilter, int? page)
            {
            var lstProduct = new List<Product>();
            if (SearchString != null)
            {
                page = 1;
            }
            else
            {
                SearchString = currentFilter;
            }
            if (!string.IsNullOrEmpty(SearchString))
            {
                lstProduct = objWebASP.Products.Where(n => n.name.Contains(SearchString)).ToList();
            }
            else
            {
                lstProduct = objWebASP.Products.ToList();
            }
            ViewBag.CurrentFilter = SearchString;
            int pageSize = 4;
            int pageNumber = (page ?? 1);
            //Sắp xếp theo id sản phảm, sản phẩm mới đưa lên đầu
            lstProduct = lstProduct.OrderByDescending(n => n.id).ToList();
            return View(lstProduct.ToPagedList(pageNumber, pageSize));
        }
        [HttpGet]
        public ActionResult Create()
        {
            this.LoadData();
            return View();
        }
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult Create(Product objProduct)
        {
            this.LoadData();
            if (ModelState.IsValid)
            {
                try
                {
                    if (objProduct.ImageUpload != null)
                    {
                        string fileName = Path.GetFileNameWithoutExtension(objProduct.ImageUpload.FileName);
                        string extension = Path.GetExtension(objProduct.ImageUpload.FileName);
                        fileName = fileName + "_" + long.Parse(DateTime.Now.ToString("yyyyyMMddhhmmss")) + extension;
                        objProduct.avatar = fileName;
                        objProduct.ImageUpload.SaveAs(Path.Combine(Server.MapPath("~/Content/images/product/"), fileName));
                        objWebASP.Products.Add(objProduct);
                        objWebASP.SaveChanges();
                        return RedirectToAction("Index");
                    }

                }
                catch (Exception)
                {

                    return RedirectToAction("Index");
                }
            }
            return View(objProduct);
            
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var objProduct = objWebASP.Products.Where(n => n.id == id).FirstOrDefault();
            return View(objProduct);
        }
        [HttpPost]
        public ActionResult Delete(Context.Product objPro)
        {
            var objProduct = objWebASP.Products.Where(n => n.id == objPro.id).FirstOrDefault();
            objWebASP.Products.Remove(objProduct);
            objWebASP.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            this.LoadData();
            var objProduct = objWebASP.Products.Where(n => n.id == id).FirstOrDefault();
            return View(objProduct);
        }

        [HttpPost]
        public ActionResult Edit(Product objProduct)
        {
            this.LoadData();
            if (objProduct.ImageUpload != null)
            {
                string fileName = Path.GetFileNameWithoutExtension(objProduct.ImageUpload.FileName);
                string extension = Path.GetExtension(objProduct.ImageUpload.FileName);
                fileName = fileName + "_" + long.Parse(DateTime.Now.ToString("yyyyyMMddhhmmss")) + extension;
                objProduct.avatar = fileName;
                objProduct.ImageUpload.SaveAs(Path.Combine(Server.MapPath("~/Content/images/product/"), fileName));
                
            }
            objWebASP.Entry(objProduct).State = EntityState.Modified;
            objWebASP.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Detail(int id)
        {
            var objProduct = objWebASP.Products.Where(n => n.id == id).FirstOrDefault();
            return View(objProduct);
        }
        void LoadData()
        {
            Common objCommon = new Common();
            var lstCat = objWebASP.Categories.ToList();
            ListtoDataTableConverter converter = new ListtoDataTableConverter();
            DataTable dtCategory = converter.toDataTable(lstCat);
            ViewBag.ListCategory = objCommon.ToSelectList(dtCategory, "id", "name");

            //Loại sản phẩm
            List<ProductType> lstProductType = new List<ProductType>();
            ProductType objProductType = new ProductType();
            objProductType.Id = 1;
            objProductType.Name = "Giảm giá sốc";
            lstProductType.Add(objProductType);

            objProductType = new ProductType();
            objProductType.Id = 2;
            objProductType.Name = "Đề xuất";
            lstProductType.Add(objProductType);
            DataTable dtProductType = converter.toDataTable(lstProductType);
            ViewBag.ProductType = objCommon.ToSelectList(dtProductType, "Id", "Name");
        }
    }
}

Website_BanHang/Areas/Admin/Views/ProductAD/Create.cshtml
@model Website_BanHang.Context.Product

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<script src="~/Scripts/ckeditor/ckeditor.js"></script>
<h2>Create</h2>

@using (Html.BeginForm("Create","ProductAD", FormMethod.Post, new {enctype="multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Product</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.id, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.id, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.avatar, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="ImageUpload" />
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.categoryID, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model=>model.categoryID,ViewBag.ListCategory as SelectList, new { @class="form-control"})
            @Html.ValidationMessageFor(model => model.categoryID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.typeID, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.typeID, ViewBag.ProductType as SelectList, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.typeID, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.fulldescription, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.fulldescription, new { htmlAttributes = new { @class = "form-control",@id= "fulldescription" } })
            <script type="text/javascript" lang="javascript">
                CKEDITOR.replace("fulldescription");
            </script>
            
            @Html.ValidationMessageFor(model => model.fulldescription, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Website_BanHang/Areas/Admin/Views/ProductAD/Delete.cshtml
@model Website_BanHang.Context.Product

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Xóa</h2>

<h3>Bạn có chắc muốn xóa sản phẩm này</h3>
<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.avatar)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.avatar)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.categoryID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.categoryID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.typeID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.typeID)
        </dd>

    </dl>

    @using (Html.BeginForm("Delete","ProductAD",FormMethod.Post,new { enctype="multipart/form-data"})) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Website_BanHang/Areas/Admin/Views/ProductAD/Detail.cshtml
@model Website_BanHang.Context.Product

@{
    ViewBag.Title = "Detail";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Detail</h2>

<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.avatar)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.avatar)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.categoryID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.categoryID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.typeID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.typeID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.fulldescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fulldescription)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Website_BanHang/Areas/Admin/Views/ProductAD/Edit.cshtml
@model Website_BanHang.Context.Product

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<script src="~/Scripts/ckeditor/ckeditor.js"></script>


<h2>Edit</h2>

@using (Html.BeginForm("Edit", "ProductAD", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.avatar, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="ImageUpload" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.categoryID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.categoryID, ViewBag.ListCategory as SelectList, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.categoryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.typeID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.typeID, ViewBag.ProductType as SelectList, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.typeID, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.fulldescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.fulldescription, new { htmlAttributes = new { @class = "form-control", @id = "fulldescription" } })
                <script type="text/javascript" lang="javascript">
                    CKEDITOR.replace("fulldescription");
                </script>

                @Html.ValidationMessageFor(model => model.fulldescription, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Website_BanHang/Areas/Admin/Views/ProductAD/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model PagedList.IPagedList<Website_BanHang.Context.Product>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Trang Sản Phẩm</h2>
@using (Html.BeginForm("Index","ProductAD",FormMethod.Get))
            {
                <p>
                    Tìm tên sản phẩm: @Html.TextBox("SearchString",ViewBag.CurrentFilter as string)
                    <input placeholder="Nhập tên sản phẩm" type="submit" value="Tìm kiếm" />
                </p>
            }

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<div style="overflow:auto">
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().avatar)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().categoryID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().typeID)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td>
            
            <img src="~/Content/images/product/@item.avatar" width="20%">
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.categoryID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.typeID)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Detail", "Detail", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>
    </div>
Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
@Html.PagedListPager(Model,page => Url.Action("Index",
 new {page, currentFilter = ViewBag.CurrentFilter }))