Website_BanHang/Areas/Admin/Controllers/CategoryADController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Website_BanHang.Context;
using static Website_BanHang.Common;

namespace Website_BanHang.Areas.Admin.Controllers
{
    public class CategoryADController : Controller
    {
        Website_BanHangEntities objWebASP = new Website_BanHangEntities();
        // GET: Admin/CategoryAD
        public ActionResult Index()
        {
            var lstCategory = objWebASP.Categories.ToList();
            return View(lstCategory);
        }
        [HttpGet]
        public ActionResult Create()
        {
            this.LoadData();
            return View();
        }
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult Create(Category objCategory)
        {
            this.LoadData();
            if (ModelState.IsValid)
            {
                try
                {
                    if (objCategory.ImageUpload != null)
                    {
                        string fileName = Path.GetFileNameWithoutExtension(objCategory.ImageUpload.FileName);
                        string extension = Path.GetExtension(objCategory.ImageUpload.FileName);
                        fileName = fileName + "_" + long.Parse(DateTime.Now.ToString("yyyyyMMddhhmmss")) + extension;
                        objCategory.avatar = fileName;
                        objCategory.ImageUpload.SaveAs(Path.Combine(Server.MapPath("~/Content/images/product/"), fileName));
                        objWebASP.Categories.Add(objCategory);
                        objWebASP.SaveChanges();
                        return RedirectToAction("Index");
                    }

                }
                catch (Exception)
                {

                    return RedirectToAction("Index");
                }
            }
            return View(objCategory);

        }
        [HttpGet]
        public ActionResult Detail(int id)
        {
            var objCategory = objWebASP.Categories.Where(n => n.id == id).FirstOrDefault();
            return View(objCategory);
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var objCategory = objWebASP.Categories.Where(n => n.id == id).FirstOrDefault();
            return View(objCategory);
        }

        [HttpPost]
        public ActionResult Edit(Category objCategory)
        {
            if (objCategory.ImageUpload != null)
            {
                string fileName = Path.GetFileNameWithoutExtension(objCategory.ImageUpload.FileName);
                string extension = Path.GetExtension(objCategory.ImageUpload.FileName);
                fileName = fileName + "_" + long.Parse(DateTime.Now.ToString("yyyyyMMddhhmmss")) + extension;
                objCategory.avatar = fileName;
                objCategory.ImageUpload.SaveAs(Path.Combine(Server.MapPath("~/Content/images/product/"), fileName));

            }
            objWebASP.Entry(objCategory).State = EntityState.Modified;
            objWebASP.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            var objCategory = objWebASP.Categories.Where(n => n.id == id).FirstOrDefault();
            return View(objCategory);
        }
        [HttpPost]
        public ActionResult Delete(Category objCate)
        {
            var objCategory = objWebASP.Categories.Where(n => n.id == objCate.id).FirstOrDefault();
            objWebASP.Categories.Remove(objCategory);
            objWebASP.SaveChanges();
            return RedirectToAction("Index");
        }

        void LoadData()
        {
            Common objCommon = new Common();
            var lstPop = objWebASP.Categories.ToList();
            ListtoDataTableConverter converter = new ListtoDataTableConverter();
            

            
            List<CategoryPopular> lstCategoryPopular = new List<CategoryPopular>();
            CategoryPopular objCategoryPopular = new CategoryPopular();
            objCategoryPopular.Id = 1;
            objCategoryPopular.Name = "Phổ biến";
            lstCategoryPopular.Add(objCategoryPopular);

            objCategoryPopular = new CategoryPopular();
            objCategoryPopular.Id = 0;
            objCategoryPopular.Name = "Không phổ biến";
            lstCategoryPopular.Add(objCategoryPopular);
            DataTable dtCategoryPopular = converter.toDataTable(lstCategoryPopular);
            ViewBag.CategoryPopular = objCommon.ToSelectList(dtCategoryPopular, "Id", "Name");
        }

    }
}

Website_BanHang/Areas/Admin/Views/CategoryAD/Create.cshtml
@model Website_BanHang.Context.Category

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "CategoryAD", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Category</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.avatar, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="ImageUpload" />
            </div>
        </div>

            <div class="form-group">
                @Html.LabelFor(model => model.popularID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.popularID, ViewBag.CategoryPopular as SelectList, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.popularID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Website_BanHang/Areas/Admin/Views/CategoryAD/Delete.cshtml
@model Website_BanHang.Context.Category

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Xóa</h2>

<h3>Bạn có chắc muốn xóa danh mục này không?</h3>
<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.avatar)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.avatar)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.popularID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.popularID)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Website_BanHang/Areas/Admin/Views/CategoryAD/Detail.cshtml
@model Website_BanHang.Context.Category

@{
    ViewBag.Title = "Detail";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Detail</h2>

<div>
    <h4>Category</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.avatar)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.avatar)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.popularID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.popularID)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Website_BanHang/Areas/Admin/Views/CategoryAD/Edit.cshtml
@model Website_BanHang.Context.Category

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "CategoryAD", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Category</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.avatar, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="ImageUpload" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.popularID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.popularID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.popularID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Website_BanHang/Areas/Admin/Views/CategoryAD/Index.cshtml
@model IEnumerable<Website_BanHang.Context.Category>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.avatar)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.popularID)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td>
            <img src="~/Content/images/category/@item.avatar" width="20%">
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.popularID)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Detail", "Detail", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>